# Generated by Django 5.2.5 on 2025-08-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='news/images/')),
                ('content', models.TextField()),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='news/content_images/')),
                ('content_video', models.FileField(blank=True, null=True, upload_to='news/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
