# Generated by Django 5.2.5 on 2025-09-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('business', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('web', 'Web-dasturlash'), ('mobile', 'Mobil va desktop ilovalar'), ('telegram', 'Telegram botlar'), ('seo', 'SEO va Daromad Oshirish'), ('ai', 'Sun’iy intellekt'), ('website', 'Web-sayt')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
