# Generated by Django 5.2.5 on 2025-08-26 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default='User', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
    ]
