# Generated by Django 5.2.5 on 2025-09-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_partner_portfolio_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
